### ISSUE TITLE
Export as fbx

### ISSUE THREAD

**Issue by F1mmel** [RenolY2/j3dview#1]
Hello,

i used your application quite a lot.
Maybe it should be possible to export the model as fbx instead just save it as bmd again.
Is something like this planned or easily implementable?

Thanks!

**Comment by RenolY2** [comment]
This is not planned and it isn't easily implementable,
If you are looking for a tool that turns BMD to FBX, try https://github.com/MeltyPlayer/FinModelUtility

**Comment by F1mmel** [comment]
Okay, thank you very much!
